version: '3.8'

services:
  puppeteer:
    build: 
      context: packages/elysia_backend
      dockerfile: ./docker/dev.dockerfile
    ports:
      - '8000:8000'
    cap_add:
      - SYS_ADMIN
    stdin_open: true
    tty: true
    # command: ["google-chrome-stable", "--no-sandbox", "--headless", "--disable-gpu", "--print-to-pdf", "https://shgrid.dev"]
    # command: ["tail", "-f", "/dev/null"]
    command: ["bun", "dev"]
    # command: ["bun", "--watch", "test"]
    init: true 
    # user: bun
    user: pptruser
    volumes:
      - ./packages/elysia_backend/src:/app/src
      - ./packages/elysia_backend/.env:/app/.env
      - ./packages/elysia_backend/test:/app/test
      - ./packages/elysia_backend/output:/output
