version: '3.8'

services:
  puppeteer:
    image: ghcr.io/connorvoisey/pdf-generator # use this for deploying on a server
    restart: always
    # build: 
    #   context: .
    #   dockerfile: docker/prod.dockerfile
    ports:
      - '3000:3000'
    cap_add:
      - SYS_ADMIN
    stdin_open: true
    tty: true
    init: true 
    user: pptruser
